version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nodejs-backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
